### ISSUE TITLE
Glove precomputed partitions

### ISSUE THREAD

**Issue by mayyxeng** [twistedcubic/learn-to-hash#4]
Sorry for being a total noob here but I do not quite understand what the input data format should be. I have downloaded the GloVe and Sift dataset from [here](https://github.com/erikbern/ann-benchmarks) and placed them inside `learn-to-hash/dataset` and modified `config` to point to this location. Executing `demo_train.py` as `python demo_train.py --glove True --sift False` I realized I needed to have the data in `NumPy` array format (`.npy`).  I tried using the `hdf5_to_binary.py` to convert my hdf5 Glove dataset to npy as I thought this file does that. Failing to execute the programs, I added this little function to `hdf5_to_binary.py` 

``` python
def toNumpy(a, file_name):
    np.save(file_name + '.npy', np.asarray(a, dtype=a.dtype))

toNumpy(dataset, sys.argv[2])
toNumpy(queries, sys.argv[3])
toNumpy(answers, sys.argv[4])

```
So I finally got the correct input format. Consequently, I could get pass some initial data format related errors but now I am stuck with this error:

```bash
/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
GloVe data must be normalized! Setting normalize_data to True...
NOTE: fast_kmeans and itq options share the same value
NOTE: fast_kmeans not enabled
n_cluster 2
Configs: Namespace(acc_thresh=0.95, compute_gt_nn=False, cplsh=True, data_dir='/home/mayy/tmp/learn-to-hash/dataset/', dataset_name='glove', dsnode_path='/home/mayy/tmp/learn-to-hash/dataset/train_dsnode', fast_kmeans=False, glove='True', glove_c=False, graph_file='knn.graph', itq=False, k=10, k_graph=10, kahip_config='strong', kmeans_use_kahip_height=-2, level2action={0: 'train'}, lr=0.0008, max_bin_count=70, n_class=2, n_clusters=2, n_epochs=1, n_hidden=512, n_input=100, n_repeat_km=3, nn_mult=5, normalize_data=True, parts_path_root='/home/mayy/tmp/learn-to-hash/dataset/partition/', pca=False, prefix10m=False, rp=False, sift=False, sift_c=False, st=False, subsample=1, write_res=True) 
 Starting data processing and training ...
torch.Size([1183514]) height: 1 level2action {0: 'train'}
graph file /home/mayy/tmp/learn-to-hash/dataset/knn.graph
Done partitioning top level!
Traceback (most recent call last):
  File "demo_train.py", line 41, in <module>
    run_kmkahip(height, opt, dataset, queryset, neighbors)
  File "/home/mayy/tmp/learn-to-hash/kahip/kmkahip.py", line 633, in run_kmkahip
    root_dsnode = create_data_tree_root(dataset, all_ranks, ds_idx, train_node, idx2bin, height, branching_l,ht2cutsz, opt)
  File "/home/mayy/tmp/learn-to-hash/kahip/kmkahip.py", line 441, in create_data_tree_root
    lines = utils.load_lines(parts_path)
  File "/home/mayy/tmp/learn-to-hash/utils.py", line 743, in load_lines
    with open(path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mayy/tmp/learn-to-hash/dataset/partition_2_strong/partition.txt
```

I checked the `runKahip` function and realized that if the glove dataset is used, then the partition files (which I do not know what they are) should already exist at `data_dir`. In fact, The function `runKahip` only executes the kahip binary in a specific case. I am really confused, where should I get these partition files?

**Comment by twistedcubic** [comment]
Hi @mayyxeng,

We are glad you are using our code.

The partition files are produced by the [KaHIP](https://github.com/KaHIP/KaHIP) graph partitioner. Can you try installing it? It's also a good idea to run it from the command line to ensure it works. 

The KaHIP repo has some nice examples. KaHIP is [called on this line](https://github.com/twistedcubic/learn-to-hash/blob/master/kahip/kmkahip.py#L82).
