### ISSUE TITLE
Cannot find module `itq`

### ISSUE THREAD

**Issue by petrizhang** [twistedcubic/learn-to-hash#7]
When I ran the file `demo_km.py`, I got the following error:
```python
Traceback (most recent call last):
  File "demo_km.py", line 6, in <module>
    from workflow_learn_kmeans import run_main, load_data, KNode
  File "/learn-to-hash/workflow_learn_kmeans.py", line 23, in <module>
    from itq import itq
```
It seems that the 'itq' module is not contained in this project,
and I cannot find any hints about the module through 'pip search'.

Could you help me solve this issue?
Thanks.

**Comment by twistedcubic** [comment]
Hi @pzque, 

We are glad you found this, it looks like the ITQ code was accidentally removed. It has been added back.
